name: myshop
description: "Project Exercise."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  faker: ^2.1.0
  flutter:
    sdk: flutter
  nested: ^1.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/blinded_maiden.jpeg
    - assets/images/Dark_anime.jpeg
  # fonts:
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato-Regular.ttf
  #       - asset: assets/fonts/Lato-Bold.ttf
  #         weight: 700
  #   - family: Anton
  #     fonts:
  #       - asset: assets/fonts/Anton-Regular.ttf
